version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181
    networks:
      - ta-net

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "art_test_topic:1:1"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - ta-net

networks:
  ta-net: